apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: catalyzer-com-tls
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: catalyzer-com-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.wiki.catalyzer.com'
  dnsNames:
#  - '*.catalyzer.com'
  - '*.wiki.catalyzer.com'
  - '*.wikibase.catalyzer.com'
  - '*.test.catalyzer.com'
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - '*.catalyzer.com'
      - '*.wiki.catalyzer.com'
      - '*.wikibase.catalyzer.com'
      - '*.test.catalyzer.com'
