apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: catalyzer-com-tls-staging
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: catalyzer-com-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.wiki.catalyzer.us'
  dnsNames:
    - 'wiki.catalyzer.us'
    - '*.wiki.catalyzer.us'
  acme:
    config:
      - dns01:
          provider: clouddns
        domains:
          - wiki.catalyzer.us
          - '*.wiki.catalyzer.us'
          - '*.wikibase.catalyzer.us'
