apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: catalyzer-com-tls
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: catalyzer-com-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.wiki.catalyzer.us'
  dnsNames:
#  - '*.catalyzer.com'
  - 'wiki.catalyzer.us'
  - '*.wiki.catalyzer.us'
  - '*.wikibase.catalyzer.us'
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - 'wiki.catalyzer.us'
      - '*.wiki.catalyzer.us'
      - '*.wikibase.catalyzer.us'
