apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: catalyzer-com-tls-staging
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: catalyzer-com-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.catalyzer.us'
  dnsNames:
    - catalyzer.us
    - '*.catalyzer.us'
    - 'wiki.catalyzer.us'
    - 'wikibase.catalyzer.us'
  acme:
    config:
      - dns01:
          provider: clouddns
        domains:
          - catalyzer.us
          - '*.catalyzer.us'
          - 'wiki.catalyzer.us'
          - 'wikibase.catalyzer.us'
