controller:
  service:
    loadBalancerIP: 34.74.91.225
    externalTrafficPolicy: Local
  resources:
    #          limits:
    #            cpu: 100m
    #            memory: 64Mi
    requests:
      cpu: 0.100
      memory: 150Mi
#      autoscaling:
#        enabled: false
#        minReplicas: 1
#        maxReplicas: 2
#        targetCPUUtilizationPercentage: 50
#        targetMemoryUtilizationPercentage: 50
