# from https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine

apiVersion: v1
kind: ServiceAccount
metadata:
  name: <admin> # TODO(developer): replace these values
  
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:catalyzer.wiki.svc.id.goog[catalyzer-wikistack/admin]" \
  catalyzer-admin@catalyzer-wikistack.iam.gserviceaccount.com
  
kubectl annotate serviceaccount \
   admin \
   iam.gke.io/gcp-service-account=catalyzer-admin@catalyzer-wikistack.iam.gserviceaccount.com
