releases:
- name: clusterissuers
  namespace: cert-manager
  chart: ./../../../charts/catalyzer-clusterissuers
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../../private/helm/default.yaml
