  
releases:
- name: clusterissuers
  namespace: cert-manager
  chart: ./../../../charts/catalyzer-clusterissuers
  values:
  - "values.yaml.gotmpl"

environments:
  default:
#create a default.yaml file in this directory to pass environment variables through values.yaml.gotmpl
    values:
      - ./../../../../private/helm/default.yaml
