releases:
- name: clusterissuers
  namespace: cert-manager
  chart: ./../../../charts/catalyzer-wikistack-clusterissuers
  values: 
  - {{.Files.Get "./values.yaml.gotmpl" | b64enc}}
#  - "./values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../../private/helm/default.yaml
