releases:
- name: clusterissuers
  namespace: cert-manager
  chart: ./../../../charts/catalyzer-wikistack-clusterissuers
  values:
#  - "./values.yaml.gotmpl"
  {{.Files.Get "./values.yaml.gotmpl" | b64enc}

environments:
  default:
    values:
      - ./../../../../private/helm/default.yaml
